name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        python-version: ['3.8']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4 (Node.js 20 support)
    
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3  # Updated to v3 (Node.js 20 support)
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test-env

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install CMake and Compiler on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++

    - name: Install Visual Studio 2019 on Windows
      if: runner.os == 'Windows'
      run: |
        conda install -c conda-forge vs2019_win-64
      # choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional --quiet --wait"

    - name: Install CMake on Windows
      if: runner.os == 'Windows'
      run: pip install cmake

    - name: Install the package
      run: |
        python setup.py compile_phreeqc
        pip install . -vvv

    - name: Run tests
      run: |
        python -m unittest discover -s tests
