name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test-env

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install CMake and Compiler on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++

    - name: Install Visual Studio 2019 on Windows
      if: runner.os == 'Windows'
      run: |
        conda install -c anaconda vs2019_win-64

    - name: Install CMake on Windows
      if: runner.os == 'Windows'
      run: pip install cmake

    - name: Install the package
      run: |
        python setup.py compile_phreeqc
        pip install . -vvv

    - name: Run tests
      run: |
        python -m unittest discover -s tests